name: "Starting backend action"
description: "Starting backend service"
inputs:
  dbuser:
    description: "dbuser"
    required: true
  dbpassword:
    description: "dbpassword"
    required: true
  db_url:
    description: "db url for mysql"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: "zulu"
        architecture: x64
    - name: Setup MySQL DB Server 8.0
      uses: ankane/setup-mysql@v1
      with:
        mysql-version: 8.0
        database: "doughnut_e2e_test"
    - run: |
        mysql -uroot -e "CREATE USER '${{ inputs.dbuser }}'@'localhost' IDENTIFIED BY '${{ inputs.dbpassword }}'"
        mysql -uroot -e "GRANT ALL PRIVILEGES ON *.* TO '${{ inputs.dbuser }}'@'localhost'"
        mysql -uroot -e "FLUSH PRIVILEGES"
      shell: bash
    - run: yarn sut &
      env:
        INPUT_DB_URL: ${{ inputs.db_url }}
      shell: bash
