name: "Starting backend action"
description: "Starting backend service"
inputs:
  java_version:
    description: "JDK Version"
    required: true
  pnpm_version:
    description: "PNMP Version"
    required: true
  mysql_version:
    description: "MySQL DB Server Version"
    required: true
  mysql_db_host_port:
    description: "MySQL DB host port"
    required: true
  mysql_db_container_port:
    description: "MySQL DB container port"
    required: true
  dbuser:
    description: "dbuser"
    required: true
  dbpassword:
    description: "dbpassword"
    required: true
  db_url:
    description: "db url for mysql"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java_version }}
        distribution: "zulu"
        architecture: x64
    - name: Setup MySQL DB Server
      uses: ankane/setup-mysql@v1
      with:
        mysql-version: ${{ inputs.mysql_version }}
        database: "doughnut_e2e_test"
    - run: |
        mysql -uroot -e "CREATE USER '${{ inputs.dbuser }}'@'localhost' IDENTIFIED BY '${{ inputs.dbpassword }}'"
        mysql -uroot -e "GRANT ALL PRIVILEGES ON *.* TO '${{ inputs.dbuser }}'@'localhost'"
        mysql -uroot -e "FLUSH PRIVILEGES"
      shell: bash
    - name: Setup pnpm & install deps
      uses: pnpm/action-setup@v3
      with:
        version: ${{ inputs.pnpm_version }}
        run_install: |
          - recursive: true
            args: [--frozen-lockfile, --strict-peer-dependencies]
    - run: pnpm backend:sut:ci &
      env:
        INPUT_DB_URL: ${{ inputs.db_url }}
      shell: bash
