// Generated by scripts/generateStoryList.mjs – do not edit

import * as _story_0 from "@/components/commons/DiffView.stories"
import * as _story_1 from "@/components/form/Quill.stories"
import * as _story_2 from "@/components/notes/accessory/NoteMoreOptionsDialog.stories"
import * as _story_3 from "@/components/recall/AnsweredQuestionComponent.stories"
import * as _story_4 from "@/components/recall/NoteUnderQuestion.stories"
import * as _story_5 from "@/components/recall/QuestionDisplay.stories"
import * as _story_6 from "@/components/toolbars/HorizontalMenu.stories"
import * as _story_7 from "@/components/toolbars/MainMenu.stories"
import * as _story_8 from "@/pages/AssimilationPageView.stories"
import * as _story_9 from "@/pages/MemoryTrackerPageView.stories"
import * as _story_10 from "@/pages/NotebookPageView.stories"
import * as _story_11 from "@/pages/NotebooksPage.stories"

export const storyFiles = [
  { filePath: "components/commons/DiffView.stories.ts", storyFile: _story_0 },
  { filePath: "components/form/Quill.stories.ts", storyFile: _story_1 },
  { filePath: "components/notes/accessory/NoteMoreOptionsDialog.stories.ts", storyFile: _story_2 },
  { filePath: "components/recall/AnsweredQuestionComponent.stories.ts", storyFile: _story_3 },
  { filePath: "components/recall/NoteUnderQuestion.stories.ts", storyFile: _story_4 },
  { filePath: "components/recall/QuestionDisplay.stories.ts", storyFile: _story_5 },
  { filePath: "components/toolbars/HorizontalMenu.stories.ts", storyFile: _story_6 },
  { filePath: "components/toolbars/MainMenu.stories.ts", storyFile: _story_7 },
  { filePath: "pages/AssimilationPageView.stories.ts", storyFile: _story_8 },
  { filePath: "pages/MemoryTrackerPageView.stories.ts", storyFile: _story_9 },
  { filePath: "pages/NotebookPageView.stories.ts", storyFile: _story_10 },
  { filePath: "pages/NotebooksPage.stories.ts", storyFile: _story_11 },
]
