/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/AdminDashboardPage': RouteRecordInfo<
      '/AdminDashboardPage',
      '/AdminDashboardPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/BazaarPage': RouteRecordInfo<
      '/BazaarPage',
      '/BazaarPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/BookReadingPage': RouteRecordInfo<
      '/BookReadingPage',
      '/BookReadingPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/CircleJoinPage': RouteRecordInfo<
      '/CircleJoinPage',
      '/CircleJoinPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/CircleShowPage': RouteRecordInfo<
      '/CircleShowPage',
      '/CircleShowPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/CirclesPage': RouteRecordInfo<
      '/CirclesPage',
      '/CirclesPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/commons/ContainerPage': RouteRecordInfo<
      '/commons/ContainerPage',
      '/commons/ContainerPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/FailureReportPage': RouteRecordInfo<
      '/FailureReportPage',
      '/FailureReportPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/FolderPage': RouteRecordInfo<
      '/FolderPage',
      '/FolderPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/HomePage': RouteRecordInfo<
      '/HomePage',
      '/HomePage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/MemoryTrackerPage': RouteRecordInfo<
      '/MemoryTrackerPage',
      '/MemoryTrackerPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/MemoryTrackerPageView': RouteRecordInfo<
      '/MemoryTrackerPageView',
      '/MemoryTrackerPageView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/MessageCenterPage': RouteRecordInfo<
      '/MessageCenterPage',
      '/MessageCenterPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/NonproductionOnlyLoginPage': RouteRecordInfo<
      '/NonproductionOnlyLoginPage',
      '/NonproductionOnlyLoginPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/NotebookGroupPage': RouteRecordInfo<
      '/NotebookGroupPage',
      '/NotebookGroupPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/NotebookGroupPageView': RouteRecordInfo<
      '/NotebookGroupPageView',
      '/NotebookGroupPageView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/NotebookPage': RouteRecordInfo<
      '/NotebookPage',
      '/NotebookPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/NotebookPageView': RouteRecordInfo<
      '/NotebookPageView',
      '/NotebookPageView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/NotebooksPage': RouteRecordInfo<
      '/NotebooksPage',
      '/NotebooksPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/NotebooksPageView': RouteRecordInfo<
      '/NotebooksPageView',
      '/NotebooksPageView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/NoteShowPage': RouteRecordInfo<
      '/NoteShowPage',
      '/NoteShowPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/RecallPage': RouteRecordInfo<
      '/RecallPage',
      '/RecallPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/AccessTokensSettingsTab': RouteRecordInfo<
      '/settings/AccessTokensSettingsTab',
      '/settings/AccessTokensSettingsTab',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/GeneralSettingsTab': RouteRecordInfo<
      '/settings/GeneralSettingsTab',
      '/settings/GeneralSettingsTab',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/RecallStatsSettingsTab': RouteRecordInfo<
      '/settings/RecallStatsSettingsTab',
      '/settings/RecallStatsSettingsTab',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/RecentSettingsTab': RouteRecordInfo<
      '/settings/RecentSettingsTab',
      '/settings/RecentSettingsTab',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/SettingsPage': RouteRecordInfo<
      '/SettingsPage',
      '/SettingsPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/UserNewRegisterPage': RouteRecordInfo<
      '/UserNewRegisterPage',
      '/UserNewRegisterPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/AdminDashboardPage.vue': {
      routes:
        | '/AdminDashboardPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/BazaarPage.vue': {
      routes:
        | '/BazaarPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/BookReadingPage.vue': {
      routes:
        | '/BookReadingPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/CircleJoinPage.vue': {
      routes:
        | '/CircleJoinPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/CircleShowPage.vue': {
      routes:
        | '/CircleShowPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/CirclesPage.vue': {
      routes:
        | '/CirclesPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/commons/ContainerPage.vue': {
      routes:
        | '/commons/ContainerPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/FailureReportPage.vue': {
      routes:
        | '/FailureReportPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/FolderPage.vue': {
      routes:
        | '/FolderPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/HomePage.vue': {
      routes:
        | '/HomePage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/MemoryTrackerPage.vue': {
      routes:
        | '/MemoryTrackerPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/MemoryTrackerPageView.vue': {
      routes:
        | '/MemoryTrackerPageView'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/MessageCenterPage.vue': {
      routes:
        | '/MessageCenterPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/NonproductionOnlyLoginPage.vue': {
      routes:
        | '/NonproductionOnlyLoginPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/NotebookGroupPage.vue': {
      routes:
        | '/NotebookGroupPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/NotebookGroupPageView.vue': {
      routes:
        | '/NotebookGroupPageView'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/NotebookPage.vue': {
      routes:
        | '/NotebookPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/NotebookPageView.vue': {
      routes:
        | '/NotebookPageView'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/NotebooksPage.vue': {
      routes:
        | '/NotebooksPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/NotebooksPageView.vue': {
      routes:
        | '/NotebooksPageView'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/NoteShowPage.vue': {
      routes:
        | '/NoteShowPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/RecallPage.vue': {
      routes:
        | '/RecallPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/AccessTokensSettingsTab.vue': {
      routes:
        | '/settings/AccessTokensSettingsTab'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/GeneralSettingsTab.vue': {
      routes:
        | '/settings/GeneralSettingsTab'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/RecallStatsSettingsTab.vue': {
      routes:
        | '/settings/RecallStatsSettingsTab'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/RecentSettingsTab.vue': {
      routes:
        | '/settings/RecentSettingsTab'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/SettingsPage.vue': {
      routes:
        | '/SettingsPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/UserNewRegisterPage.vue': {
      routes:
        | '/UserNewRegisterPage'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
