/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/AdminDashboardPage': RouteRecordInfo<'/AdminDashboardPage', '/AdminDashboardPage', Record<never, never>, Record<never, never>>,
    '/AnsweredQuestionPage': RouteRecordInfo<'/AnsweredQuestionPage', '/AnsweredQuestionPage', Record<never, never>, Record<never, never>>,
    '/AssessmentHistoryPage': RouteRecordInfo<'/AssessmentHistoryPage', '/AssessmentHistoryPage', Record<never, never>, Record<never, never>>,
    '/AssessmentPage': RouteRecordInfo<'/AssessmentPage', '/AssessmentPage', Record<never, never>, Record<never, never>>,
    '/BazaarPage': RouteRecordInfo<'/BazaarPage', '/BazaarPage', Record<never, never>, Record<never, never>>,
    '/CircleJoinPage': RouteRecordInfo<'/CircleJoinPage', '/CircleJoinPage', Record<never, never>, Record<never, never>>,
    '/CircleShowPage': RouteRecordInfo<'/CircleShowPage', '/CircleShowPage', Record<never, never>, Record<never, never>>,
    '/commons/ContainerPage': RouteRecordInfo<'/commons/ContainerPage', '/commons/ContainerPage', Record<never, never>, Record<never, never>>,
    '/commons/TeleportToHeadStatus': RouteRecordInfo<'/commons/TeleportToHeadStatus', '/commons/TeleportToHeadStatus', Record<never, never>, Record<never, never>>,
    '/FailureReportPage': RouteRecordInfo<'/FailureReportPage', '/FailureReportPage', Record<never, never>, Record<never, never>>,
    '/HomePage': RouteRecordInfo<'/HomePage', '/HomePage', Record<never, never>, Record<never, never>>,
    '/InitialReviewPage': RouteRecordInfo<'/InitialReviewPage', '/InitialReviewPage', Record<never, never>, Record<never, never>>,
    '/NonproductionOnlyLoginPage': RouteRecordInfo<'/NonproductionOnlyLoginPage', '/NonproductionOnlyLoginPage', Record<never, never>, Record<never, never>>,
    '/NotebooksPage': RouteRecordInfo<'/NotebooksPage', '/NotebooksPage', Record<never, never>, Record<never, never>>,
    '/NoteShowPage': RouteRecordInfo<'/NoteShowPage', '/NoteShowPage', Record<never, never>, Record<never, never>>,
    '/RepeatPage': RouteRecordInfo<'/RepeatPage', '/RepeatPage', Record<never, never>, Record<never, never>>,
    '/ReviewHome': RouteRecordInfo<'/ReviewHome', '/ReviewHome', Record<never, never>, Record<never, never>>,
    '/UserNewRegisterPage': RouteRecordInfo<'/UserNewRegisterPage', '/UserNewRegisterPage', Record<never, never>, Record<never, never>>,
  }
}
