packages:
  - frontend
  - mcp-server
  - cli
  - packages/doughnut-api
  - packages/doughnut-test-fixtures
  - packages/generated/doughnut-backend-api

onlyBuiltDependencies:
  - '@badeball/cypress-cucumber-preprocessor'
  - '@biomejs/biome'
  - '@parcel/watcher'
  - canvas
  - core-js
  - core-js-pure
  - cypress
  - ejs
  - esbuild
  - github_action_sound
  - protobufjs
  - tesseract.js

ignoredBuiltDependencies:
  - es5-ext
