# TEMPORARY MEASUREMENT MACHINERY — SEED-034#story-4, slices 2-3 and 13.
#
# This is not a product test and carries no acceptance promise. It exists to
# observe ordinary note-content saves in a large synchronized notebook so the
# story's save-speed comparison rests on evidence. Slice 14 deletes this file
# together with e2e_test/step_definitions/note_save_measurement.ts,
# e2e_test/start/pageObjects/noteSaveMeasurement.ts,
# e2e_test/start/pageObjects/noteSaveMeasurementNotebookTask.ts,
# e2e_test/config/noteSaveMeasurement.ts, its registration in
# e2e_test/config/common.ts and its entry in
# scripts/isolated-cypress-active-specs.mjs.
#
# It runs only on request: `@wip` keeps it out of CI, and it needs a payload
# generated by scripts/profiling/generate-note-save-fixture.mjs.
#
#   NOTE_SAVE_FIXTURE_NOTES=200 NOTE_SAVE_FIXTURE_FOLDERS=5 \
#     CURSOR_DEV=true nix develop -c \
#     node scripts/profiling/generate-note-save-fixture.mjs /tmp/note-save-fixture
#   NOTE_SAVE_FIXTURE_DIR=/tmp/note-save-fixture \
#     CURSOR_DEV=true nix develop -c pnpm cy:run \
#     --spec e2e_test/features/note_creation_and_update/note_save_measurement.feature
#
# Measured numbers are printed by the runner as `note-save-measurement {...}`
# lines: seeding wall-clock, the captured Portable export, then one line per
# save with both boundaries. Sample 0 is the discarded warm-up.
#
# `NOTE_SAVE_EXPORT_OUT` names the file the notebook's Portable export ZIP is
# written to; the two sides of a comparison must not share one path.
#
# A payload generated with NOTE_SAVE_FIXTURE_ATTACHMENTS=realistic also has
# root attachment files, which are published through Git before any measured
# save; a payload without them publishes nothing.
#
# Seeding imports the fixture's final state and re-snapshots the notebook's
# accepted baseline; it does not replay the fixture's `revisions`, so accepted
# history is one commit deep on every side that seeds this way.
@wip
Feature: Note save measurement
  To decide whether note saving in a large synchronized notebook is fast
  enough, I want ordinary content saves observed with the real debounce and
  the real serialized persist chain, reporting the wait an author feels and
  the storage request separately.

  Background:
    Given I am logged in as an existing user
    And I have the generated large synchronized measurement notebook
    And the measurement notebook's root holds the fixture's attachments, published through Git

  Scenario: Ordinary content saves in a large synchronized notebook
    When I capture the measurement notebook's Portable export
    And I warm up the measured save path
    And I measure save 1 of note content that keeps its existing wiki links
    And I measure save 2 of note content that keeps its existing wiki links
    And I measure save 3 of note content that keeps its existing wiki links
    And I measure save 4 of note content that keeps its existing wiki links
    And I measure save 5 of note content that keeps its existing wiki links
    And I measure save 1 of note content that adds a wiki link
    And I measure save 2 of note content that adds a wiki link
    And I measure save 3 of note content that adds a wiki link
    And I measure save 4 of note content that adds a wiki link
    And I measure save 5 of note content that adds a wiki link
    Then each measured save reports its debounce and its request separately
    And the measured note reloads with every measured edit and a live link
