/**
 * TEMPORARY MEASUREMENT MACHINERY — SEED-034#story-4, slices 2-3.
 * Deleted together with `note_save_measurement.feature` in slice 14.
 *
 * Node-side tasks only: hand the disposable fixture payload generated by
 * `scripts/profiling/generate-note-save-fixture.mjs` to the browser, keep the
 * captured notebook export as a file, and print measured samples on the
 * runner's stdout so a run's numbers are readable without a benchmark
 * framework, a report file or a production timing hook.
 */
import assert from 'node:assert/strict'
import { execFileSync } from 'node:child_process'
import {
  copyFileSync,
  existsSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

const FIXTURE_DIR_ENV = 'NOTE_SAVE_FIXTURE_DIR'
const EXPORT_OUT_ENV = 'NOTE_SAVE_EXPORT_OUT'

function fixtureDirectory(): string {
  const dir = process.env[FIXTURE_DIR_ENV]
  if (!dir) {
    throw new Error(
      `${FIXTURE_DIR_ENV} must point at a directory produced by scripts/profiling/generate-note-save-fixture.mjs`
    )
  }
  return dir
}

/**
 * The one home for the part of the generated `fixture.json` this measurement
 * consumes, shared with the browser side by type only; the generator remains
 * the authority for the rest of the payload.
 */
export type NoteSaveFixture = {
  notebook: string
  notes: { Title: string; Folder: string; Content: string }[]
}

/** The measured notebook, addressed as the logged-in browser user. */
type NotebookRequest = { origin: string; notebookId: number; cookie: string }

export function noteSaveMeasurementTasks() {
  return {
    /** The generated `fixture.json`, addressed by an absolute disposable path. */
    noteSaveMeasurementFixture(): NoteSaveFixture {
      return JSON.parse(
        readFileSync(join(fixtureDirectory(), 'fixture.json'), 'utf8')
      ) as NoteSaveFixture
    },

    /**
     * The notebook's own Portable export, kept as a file so the two sides of
     * the reconstructed comparison can be diffed path by path outside the run.
     * `NOTE_SAVE_EXPORT_OUT` names the file; the two sides must not share one.
     * Downloaded here, not through the browser (slice 13): an export holding
     * attachments is megabytes the Cypress command log would keep.
     */
    async saveNoteSaveMeasurementExport({
      origin,
      notebookId,
      cookie,
    }: NotebookRequest) {
      const out =
        process.env[EXPORT_OUT_ENV] ?? join(fixtureDirectory(), 'export.zip')
      const response = await fetch(
        `${origin}/api/notebooks/${notebookId}/export`,
        { headers: { Cookie: cookie } }
      )
      assert.equal(response.status, 200, 'notebook export')
      const zip = Buffer.from(await response.arrayBuffer())
      writeFileSync(out, zip)
      console.log(
        `note-save-measurement ${JSON.stringify({ exportedTo: out, zipBytes: zip.length })}`
      )
      return null
    },

    /**
     * TEMPORARY (slice 13): adds the fixture's `attachments/` files at the
     * notebook root the way an author does - clone the accepted history,
     * commit the files, publish the proposal bundle - so they reach the
     * notebook through the product's own Git publication. A fixture without
     * attachments publishes nothing, so the with/without runs share one
     * feature.
     */
    async publishNoteSaveMeasurementAttachments({
      origin,
      notebookId,
      cookie,
    }: NotebookRequest) {
      const source = join(fixtureDirectory(), 'attachments')
      if (!existsSync(source)) {
        console.log(
          `note-save-measurement ${JSON.stringify({ publishedRootAttachments: 0 })}`
        )
        return null
      }
      const work = mkdtempSync(join(tmpdir(), 'note-save-attachments-'))
      const endpoint = `${origin}/api/notebooks/${notebookId}/git-bundle`
      const accepted = await fetch(endpoint, { headers: { Cookie: cookie } })
      assert.equal(accepted.status, 200, 'accepted history download')
      const acceptedBundle = join(work, 'accepted.bundle')
      writeFileSync(acceptedBundle, Buffer.from(await accepted.arrayBuffer()))
      const checkout = join(work, 'checkout')
      execFileSync('git', [
        'clone',
        '-q',
        '-b',
        'main',
        acceptedBundle,
        checkout,
      ])
      const git = (...args: string[]) =>
        execFileSync('git', ['-C', checkout, ...args], {
          encoding: 'utf8',
        }).trim()
      const files = readdirSync(source).sort()
      for (const file of files)
        copyFileSync(join(source, file), join(checkout, file))
      git('add', '--', ...files)
      git(
        '-c',
        'user.name=Note Save Measurement',
        '-c',
        'user.email=measurement@example.com',
        'commit',
        '-q',
        '-m',
        'Add root attachments'
      )
      const proposal = join(work, 'proposal.bundle')
      git('bundle', 'create', proposal, 'main')
      const body = readFileSync(proposal)
      const startedAt = Date.now()
      const published = await fetch(
        `${endpoint}?expectedHead=${git('rev-parse', 'HEAD^')}`,
        {
          method: 'POST',
          headers: {
            Cookie: cookie,
            'Content-Type': 'application/x-git-bundle',
          },
          body,
        }
      )
      const response = await published.text()
      const publishMs = Date.now() - startedAt
      assert.equal(published.status, 200, response)
      const sizes = Object.fromEntries(
        files.map((file) => [file, statSync(join(source, file)).size])
      )
      console.log(
        `note-save-measurement ${JSON.stringify({
          publishedRootAttachments: files.length,
          totalBytes: Object.values(sizes).reduce((sum, size) => sum + size, 0),
          proposalBundleBytes: body.length,
          publishMs,
          acceptedHead: response,
          sizes,
        })}`
      )
      rmSync(work, { recursive: true, force: true })
      return null
    },

    reportNoteSaveMeasurement(sample: Record<string, unknown>) {
      console.log(`note-save-measurement ${JSON.stringify(sample)}`)
      return null
    },
  }
}
