/**
 * TEMPORARY MEASUREMENT MACHINERY — SEED-034#story-4, slices 2-3.
 * Deleted together with `note_save_measurement.feature` in slice 14.
 *
 * Node-side tasks only: hand the disposable fixture payload generated by
 * `scripts/profiling/generate-note-save-fixture.mjs` to the browser, keep the
 * captured notebook export as a file, and print measured samples on the
 * runner's stdout so a run's numbers are readable without a benchmark
 * framework, a report file or a production timing hook.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const FIXTURE_DIR_ENV = 'NOTE_SAVE_FIXTURE_DIR'
const EXPORT_OUT_ENV = 'NOTE_SAVE_EXPORT_OUT'

function fixtureDirectory(): string {
  const dir = process.env[FIXTURE_DIR_ENV]
  if (!dir) {
    throw new Error(
      `${FIXTURE_DIR_ENV} must point at a directory produced by scripts/profiling/generate-note-save-fixture.mjs`
    )
  }
  return dir
}

/**
 * The one home for the part of the generated `fixture.json` this measurement
 * consumes, shared with the browser side by type only; the generator remains
 * the authority for the rest of the payload.
 */
export type NoteSaveFixture = {
  notebook: string
  notes: { Title: string; Folder: string; Content: string }[]
}

export function noteSaveMeasurementTasks() {
  return {
    /** The generated `fixture.json`, addressed by an absolute disposable path. */
    noteSaveMeasurementFixture(): NoteSaveFixture {
      return JSON.parse(
        readFileSync(join(fixtureDirectory(), 'fixture.json'), 'utf8')
      ) as NoteSaveFixture
    },

    /**
     * The notebook's own Portable export, kept as a file so the two sides of
     * the reconstructed comparison can be diffed path by path outside the run.
     * `NOTE_SAVE_EXPORT_OUT` names the file; the two sides must not share one.
     */
    saveNoteSaveMeasurementExport(zipBase64: string) {
      const out =
        process.env[EXPORT_OUT_ENV] ?? join(fixtureDirectory(), 'export.zip')
      const zip = Buffer.from(zipBase64, 'base64')
      writeFileSync(out, zip)
      console.log(
        `note-save-measurement ${JSON.stringify({ exportedTo: out, zipBytes: zip.length })}`
      )
      return null
    },

    reportNoteSaveMeasurement(sample: Record<string, unknown>) {
      console.log(`note-save-measurement ${JSON.stringify(sample)}`)
      return null
    },
  }
}
