/**
 * TEMPORARY MEASUREMENT MACHINERY — SEED-034#story-4, slices 2-3.
 * Deleted together with `note_save_measurement.feature` in slice 14.
 *
 * Two node-side tasks only: hand the disposable fixture payload generated by
 * `scripts/profiling/generate-note-save-fixture.mjs` to the browser, and print
 * measured samples on the runner's stdout so a run's numbers are readable
 * without a benchmark framework, a report file or a production timing hook.
 */
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

const FIXTURE_DIR_ENV = 'NOTE_SAVE_FIXTURE_DIR'

/**
 * The one home for the part of the generated `fixture.json` this measurement
 * consumes, shared with the browser side by type only; the generator remains
 * the authority for the rest of the payload.
 */
export type NoteSaveFixture = {
  notebook: string
  notes: { Title: string; Folder: string; Content: string }[]
}

export function noteSaveMeasurementTasks() {
  return {
    /** The generated `fixture.json`, addressed by an absolute disposable path. */
    noteSaveMeasurementFixture(): NoteSaveFixture {
      const dir = process.env[FIXTURE_DIR_ENV]
      if (!dir) {
        throw new Error(
          `${FIXTURE_DIR_ENV} must point at a directory produced by scripts/profiling/generate-note-save-fixture.mjs`
        )
      }
      return JSON.parse(
        readFileSync(join(dir, 'fixture.json'), 'utf8')
      ) as NoteSaveFixture
    },

    reportNoteSaveMeasurement(sample: Record<string, unknown>) {
      console.log(`note-save-measurement ${JSON.stringify(sample)}`)
      return null
    },
  }
}
