CREATE TABLE failure_report (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    error_name VARCHAR(100) NOT NULL,
    error_detail VARCHAR(1000) NOT NULL,
    issue_number DECIMAL ,
    created_datetime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 AUTO_INCREMENT=1;