-- This file is here to serve as a placeholder for future database migrations.
--
-- Please create a new migration file for any future database changes.
-- The file name should be in the format `V{version}__{description}.sql`
-- For example: `V300000172__change_a_field_type.sql`
