import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const srcDir = path.join(__dirname, "..", "src")

const storyFiles = []
function walk(dir, base = "") {
  for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {
    const rel = base ? `${base}/${ent.name}` : ent.name
    const full = path.join(dir, ent.name)
    if (ent.isDirectory()) {
      walk(full, rel)
    } else if (
      ent.name.endsWith(".stories.ts") ||
      ent.name.endsWith(".stories.tsx")
    ) {
      const importPath = `@/${rel.replace(/\.(tsx?|jsx?|mjs)$/, "")}`
      storyFiles.push({ relPath: rel, importPath })
    }
  }
}
walk(srcDir)

const lines = [
  "// Generated by scripts/generateStoryList.mjs – do not edit",
  "",
  ...storyFiles.map(
    (_, i) => `import * as _story_${i} from "${storyFiles[i].importPath}"`
  ),
  "",
  "export const storyFiles = [",
  ...storyFiles.map(
    (s, i) => `  { filePath: "${s.relPath}", storyFile: _story_${i} },`
  ),
  "]",
]
const outPath = path.join(__dirname, "..", "storyFiles.generated.ts")
fs.writeFileSync(outPath, `${lines.join("\n")}\n`, "utf8")
