name: "Google Cloud Auth & SDK Setup"
description: "gcloud auth & gcloud-sdk setup"
inputs:
  credentials_json:
    description: "GCloud Credentials JSON"
    required: true
runs:
  using: "composite"
  steps:
    - name: GCP Auth with Service Account
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ inputs.credentials_json }}
    - name: Set up GCP SDK
      uses: google-github-actions/setup-gcloud@v1
