name: "Setup NodeJS"
description: "Setup NodeJS"
inputs:
  node-version:
    description: "NodeJS Version"
    required: true
    default: "21"
runs:
  using: "composite"
  steps:
    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - name: Setup pnpm & install deps
      uses: pnpm/action-setup@v2
      with:
        version: 8.12.0
        run_install: |
          - recursive: true
            args: [--frozen-lockfile, --strict-peer-dependencies]
