Feature: Understanding Check
  As a learner, when I start assimilating a note, I want to have the key
  points I should understand from the note generated by AI,
  and delete selected points to have AI remove related content from note details.
  So that I can check whether I truly understood the important points,
  especially when the note is long.

  Background:
    Given I am logged in as an existing user
    And I have a notebook with the head note "Sample" and details "A. B. C. D. E."

  @usingMockedOpenAiService
  Scenario: Generate understanding checklist for a note
    Given OpenAI generates understanding checklist with points:
      | A |
      | B |
      | C |
      | D |
      | E |
    When I start assimilating "Sample"
    Then I should see an understanding checklist with a maximum of 5 points

  @usingMockedOpenAiService
  Scenario: Delete selected understanding points
    Given OpenAI generates understanding checklist with points:
      | A |
      | B |
      | C |
      | D |
      | E |
    And OpenAI returns the following details when requested to delete points:
      | B. D. E. |
    When I start assimilating "Sample"
    And I delete understanding points 0 and 2
    Then the note details on the current page should be "B. D. E."
