#!/usr/bin/env bash
set -euo pipefail

# Get the script directory and project root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${PROJECT_ROOT}"

GENERATED_DIR="generated/backend"
CORE_DIR="${GENERATED_DIR}/core"

# Ensure directories exist
mkdir -p "${CORE_DIR}"

# Create BaseHttpRequest.ts
cat > "${CORE_DIR}/BaseHttpRequest.ts" << 'EOF'
/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { ApiRequestOptions } from './ApiRequestOptions';
import type { CancelablePromise } from './CancelablePromise';
import type { OpenAPIConfig } from './OpenAPI';

export abstract class BaseHttpRequest {

    constructor(public readonly config: OpenAPIConfig) {}

    public abstract request<T>(options: ApiRequestOptions): CancelablePromise<T>;
}
EOF

# Create FetchHttpRequest.ts
cat > "${CORE_DIR}/FetchHttpRequest.ts" << 'EOF'
/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { ApiRequestOptions } from './ApiRequestOptions';
import { BaseHttpRequest } from './BaseHttpRequest';
import type { CancelablePromise } from './CancelablePromise';
import type { OpenAPIConfig } from './OpenAPI';
import { request as __request } from './request';

export class FetchHttpRequest extends BaseHttpRequest {

    constructor(config: OpenAPIConfig) {
        super(config);
    }

    /**
     * Request method
     * @param options The request options from the service
     * @returns CancelablePromise<T>
     * @throws ApiError
     */
    public override request<T>(options: ApiRequestOptions): CancelablePromise<T> {
        return __request(this.config, options);
    }
}
EOF

# Update index.ts to export everything needed
cat > "${GENERATED_DIR}/index.ts" << 'EOF'
// This file is auto-generated by @hey-api/openapi-ts
// Additional exports added by post-generate-backend-api.sh for compatibility

export { ApiError } from './core/ApiError';
export { BaseHttpRequest } from './core/BaseHttpRequest';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI, type OpenAPIConfig } from './core/OpenAPI';

export * from './schemas.gen';
export * from './services.gen';
export * from './types.gen';
EOF

echo "Post-generation compatibility files created successfully"

