#!/usr/bin/env bash
set -euo pipefail

# Get the script directory and project root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${PROJECT_ROOT}"

GENERATED_DIR="generated/backend"
CORE_DIR="${GENERATED_DIR}/core"

# Ensure directories exist
mkdir -p "${CORE_DIR}"

# Create BaseHttpRequest.ts
cat > "${CORE_DIR}/BaseHttpRequest.ts" << 'EOF'
/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { ApiRequestOptions } from './ApiRequestOptions';
import type { CancelablePromise } from './CancelablePromise';
import type { OpenAPIConfig } from './OpenAPI';

export abstract class BaseHttpRequest {

    constructor(public readonly config: OpenAPIConfig) {}

    public abstract request<T>(options: ApiRequestOptions): CancelablePromise<T>;
}
EOF

# Create FetchHttpRequest.ts
cat > "${CORE_DIR}/FetchHttpRequest.ts" << 'EOF'
/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { ApiRequestOptions } from './ApiRequestOptions';
import { BaseHttpRequest } from './BaseHttpRequest';
import type { CancelablePromise } from './CancelablePromise';
import type { OpenAPIConfig } from './OpenAPI';
import { request as __request } from './request';

export class FetchHttpRequest extends BaseHttpRequest {

    constructor(config: OpenAPIConfig) {
        super(config);
    }

    /**
     * Request method
     * @param options The request options from the service
     * @returns CancelablePromise<T>
     * @throws ApiError
     */
    public override request<T>(options: ApiRequestOptions): CancelablePromise<T> {
        return __request(this.config, options);
    }
}
EOF

# Update index.ts to export everything needed
cat > "${GENERATED_DIR}/index.ts" << 'EOF'
// This file is auto-generated by @hey-api/openapi-ts
// Additional exports added by post-generate-backend-api.sh for compatibility

export { DoughnutApi } from './DoughnutApi';

export { ApiError } from './core/ApiError';
export { BaseHttpRequest } from './core/BaseHttpRequest';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI, type OpenAPIConfig } from './core/OpenAPI';

export * from './schemas.gen';
export * from './services.gen';
export * from './types.gen';

// Export models with namespaces for compatibility
export { NoteTopology } from './models/NoteTopology';
export { DummyForGeneratingTypes } from './models/DummyForGeneratingTypes';

// Export individual service classes for compatibility
export { AssimilationControllerService } from './services/AssimilationControllerService';
export { McpNoteCreationControllerService } from './services/McpNoteCreationControllerService';
export { RestAiAudioControllerService } from './services/RestAiAudioControllerService';
export { RestAiControllerService } from './services/RestAiControllerService';
export { RestAssessmentControllerService } from './services/RestAssessmentControllerService';
export { RestBazaarControllerService } from './services/RestBazaarControllerService';
export { RestCertificateControllerService } from './services/RestCertificateControllerService';
export { RestCircleControllerService } from './services/RestCircleControllerService';
export { RestConversationMessageControllerService } from './services/RestConversationMessageControllerService';
export { RestCurrentUserInfoControllerService } from './services/RestCurrentUserInfoControllerService';
export { RestFailureReportControllerService } from './services/RestFailureReportControllerService';
export { RestFineTuningDataControllerService } from './services/RestFineTuningDataControllerService';
export { RestGlobalSettingsControllerService } from './services/RestGlobalSettingsControllerService';
export { RestHealthCheckControllerService } from './services/RestHealthCheckControllerService';
export { RestLinkControllerService } from './services/RestLinkControllerService';
export { RestMemoryTrackerControllerService } from './services/RestMemoryTrackerControllerService';
export { RestNotebookCertificateApprovalControllerService } from './services/RestNotebookCertificateApprovalControllerService';
export { RestNotebookControllerService } from './services/RestNotebookControllerService';
export { RestNoteControllerService } from './services/RestNoteControllerService';
export { RestNoteCreationControllerService } from './services/RestNoteCreationControllerService';
export { RestPredefinedQuestionControllerService } from './services/RestPredefinedQuestionControllerService';
export { RestRecallPromptControllerService } from './services/RestRecallPromptControllerService';
export { RestRecallsControllerService } from './services/RestRecallsControllerService';
export { RestSearchControllerService } from './services/RestSearchControllerService';
export { RestSubscriptionControllerService } from './services/RestSubscriptionControllerService';
export { RestTextContentControllerService } from './services/RestTextContentControllerService';
export { RestUserControllerService } from './services/RestUserControllerService';
export { RestWikidataControllerService } from './services/RestWikidataControllerService';
export { TestabilityRestControllerService } from './services/TestabilityRestControllerService';
EOF

echo "Post-generation compatibility files created successfully"

