@usingMockedOpenAiService
Feature: User Contests Question generation by AI
  As a learner, I want to contest the question generated by AI, so that I can get a better question for my note.

  Background:
    Given I am logged in as an existing user
    And I have a notebook with the head note "Scuba Diving"
    And OpenAI generates this as first question:
      | Question Stem   | Correct Choice | Incorrect Choice 1 | Incorrect Choice 2 |
      | First question  | Rescue Diver   | Divemaster         | Open Water Diver   |
    And OpenAI generates this as second question:
      | Question Stem    | Correct Choice | Incorrect Choice 1 | Incorrect Choice 2 |
      | Second question  | Rescue Diver   | Divemaster         | Open Water Diver   |

  Scenario Outline: The generated question should be contested internally
    Given OpenAI evaluates the question as <Legitimate Question>
    And I assimilated one note "Scuba Diving" on day 1
    When I am recalling my note on day 2
    Then I should be asked "<Current Question>"

    Examples:
    | Legitimate Question | Current Question |
    | legitimate          | First question   |
    | not legitimate      | Second question  |

  Scenario: I should be able to contest a question
    Given OpenAI evaluates the question as not legitimate
    And I assimilated one note "Scuba Diving" on day 1
    And I am recalling my note on day 2
    When I contest the question
    Then I should be asked "Second question"
