@usingMockedOpenAiService
Feature: User Contests Question generation by AI
  As a learner, I want to contest the question generated by AI, so that I can get a better question for my note.

  Background:
    Given I am logged in as an existing user
    And I have a notebook with the head note "Scuba Diving"
    Given OpenAI generates this as first question:
      | Question Stem   | Correct Choice | Incorrect Choice 1 | Incorrect Choice 2 |
      | First question  | Rescue Diver   | Divemaster         | Open Water Diver   |
    And OpenAI generates this as second question:
      | Question Stem    | Correct Choice | Incorrect Choice 1 | Incorrect Choice 2 |
      | Second question  | Rescue Diver   | Divemaster         | Open Water Diver   |

  Scenario Outline: The generated question should be contested internally
    Given OpenAI evaluates the question as <Legitimate Question>
    And I learned one note "Scuba Diving" on day 1
    When I am recalling my note on day 2
    And I should be asked "<Current Question>"

    Examples:
    | Legitimate Question |  Current Question |
    | legitamate          |  First question   |
    | not legitamate      |  Second question  |

  Scenario: I should be able to contest a question
    # this is a difference when running this test local and in CI server 
    # in local, this test fails because there are two second questions displayed.
    # Moving the "OpenAI evaluates the question as not legitamate" to right before "I contest the question" fixes the issue.
    # But it passes the test in CI server.
    And OpenAI evaluates the question as not legitamate
    Given I learned one note "Scuba Diving" on day 1
    And I am recalling my note on day 2
    When I contest the question
    Then I should be asked "Second question"
